trigger:
  branches:
    include:
      - master
  paths:
    include:
    - src/*

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

variables:
  RestoreBuildProjects: '**/*.csproj'
  TestProjects: '**/*[Tt]ests/*.csproj'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.0.x'
  inputs:
    version: 3.0.x

- script: 'dotnet user-secrets set ZeroBounceApiKey $(ZeroBounceApiKey) --project src\ZeroBounce.RestClient.Tests\ZeroBounce.RestClient.Tests.csproj'
  displayName: 'Command Line Script'

- task: DotNetCoreCLI@2
  displayName: 'Set User Secrets'
  inputs:
    command: custom
    projects: '$(RestoreBuildProjects)'
    custom: 'user-secrets set ZeroBounceApiKey $(ZeroBounceApiKey)'
  enabled: false

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    nobuild: true
    versioningScheme: byPrereleaseNumber
    buildProperties: 'SymbolPackageFormat=snupkg'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
